# Generated by Django 4.1 on 2025-08-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartprediction',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
