# Generated by Django 4.1 on 2025-08-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0002_heartprediction_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='heartprediction',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
