# Generated by Django 6.0.6 on 2026-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0005_adminuser_patientuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heartprediction',
            name='probability',
        ),
        migrations.AlterField(
            model_name='heartprediction',
            name='prediction',
            field=models.CharField(max_length=25),
        ),
    ]
